// vERSIONAMENTO DE CÓDIGOS
// historico de mudanças, colaboração, ramos (branches), fusões (merges), rastreabilidade, backup
// VSC (sistemas de controle de versão) - centralizado e distribuido

// GIT (é um vsc) open source (codigo aberto, todos podem ver e rodar) software descktop  de controle de versão que pode se conectar a um servidor remoto
// GITHUB é um servidor remoto, plataforma de hospedagem de código para controle de versão com git. (repositorio remoto e plataforma de rede social para devs)
