// console.log('"hello worold"')
// console.log("'hello worold'")
// console.log(`hello worold`)

// console.log(1,5)
// console.log("10")
// console.log(typeof("10"))
// console.log(typeof(10))

// console.log(typeof(10), 1000, 'karol')

// // name='karol'
// let name = 'karol'
// var anothername = 'karol'

// const CITY = 'Porto Alegre'

// let test = 'teste'
// console.log(test)

// let myNull = null
// console.log(myNull)

// let myBoolean = true
// console.log(typeof(myBoolean))

// let num1 = 10
// let num2 = 5

// console.log(num1 + num2)
// console.log(num1 - num2)
// console.log(num1 / num2)
// console.log(num1 * num2)
// console.log(num1 ** num2)
// console.log(num1 % num2)

// ()
// **
// * / %
// + -

// let numTest = '5'
// console.log(numTest + 10)
// let numTest2 = parseInt(numTest)
// console.log(numTest2 + 10)

// let numTest = '5'
// console.log(parseInt(numTest) + 10)

// let counter = 1
// counter = counter + 1
// counter = counter - 1
// counter++
// counter--

// console.log(counter)
// console.log(counter++)
// console.log(counter)
// console.log(++counter)

// let step = 2
// counter = counter + step
// counter += step

// counter = counter - step
// counter -= step

// counter = counter * step
// counter *= step

// counter = counter / step
// counter /= step
