// FRONT-END DEVELOPMENT
// internet surge após segunda guerra mundial (DARPA)
// WWW grupo de servidores que seguem o protocolo HTTP especializados em hipertexto (capaz de ler documento HTML)
// transferencia de dados - ondas digitais ou ondas quadradas que representam 0 ou 1
// distribuição de rede ou sinal - onda senoidal ou sinal analogico
// Modem (Modulação e Demodulação) - transforma sinal analogico em digital e vicev.

// https://en.wikipedia.org/wiki/internet#terminology
// protocolo/subdominio.nomeDoDominio.topLevelDomain/caminho/ancoraOUparametros
// URL - sequencia de texto que especifica onde um recurso pode ser encontrado na internet
// http ou www - chamamos de endereço web ou link

// HTML - estrutura da pagina web
// CSS - estilo 
// JS - comportamento